#include "csr/trsm_csr_n_hi_col.hpp"
#include "csr/trsm_csr_n_hi_row.hpp"
#include "csr/trsm_csr_n_lo_col.hpp"
#include "csr/trsm_csr_n_lo_row.hpp"
#include "csr/trsm_csr_u_hi_col.hpp"
#include "csr/trsm_csr_u_hi_row.hpp"
#include "csr/trsm_csr_u_lo_col.hpp"
#include "csr/trsm_csr_u_lo_row.hpp"

#include "csr/trsm_csr_n_hi_col_trans.hpp"
#include "csr/trsm_csr_n_hi_row_trans.hpp"
#include "csr/trsm_csr_n_lo_col_trans.hpp"
#include "csr/trsm_csr_n_lo_row_trans.hpp"
#include "csr/trsm_csr_u_hi_col_trans.hpp"
#include "csr/trsm_csr_u_hi_row_trans.hpp"
#include "csr/trsm_csr_u_lo_col_trans.hpp"
#include "csr/trsm_csr_u_lo_row_trans.hpp"

#include "csr/trsm_csr_n_hi_col_conj.hpp"
#include "csr/trsm_csr_n_hi_row_conj.hpp"
#include "csr/trsm_csr_n_lo_col_conj.hpp"
#include "csr/trsm_csr_n_lo_row_conj.hpp"
#include "csr/trsm_csr_u_hi_col_conj.hpp"
#include "csr/trsm_csr_u_hi_row_conj.hpp"
#include "csr/trsm_csr_u_lo_col_conj.hpp"
#include "csr/trsm_csr_u_lo_row_conj.hpp"

#include "csr/diagsm_csr_n_col.hpp"
#include "csr/diagsm_csr_n_row.hpp"
#include "csr/diagsm_csr_u_col.hpp"
#include "csr/diagsm_csr_u_row.hpp"

#include "bsr/trsm_bsr_n_hi_col.hpp"
#include "bsr/trsm_bsr_n_hi_row.hpp"
#include "bsr/trsm_bsr_n_lo_col.hpp"
#include "bsr/trsm_bsr_n_lo_row.hpp"
#include "bsr/trsm_bsr_u_hi_col.hpp"
#include "bsr/trsm_bsr_u_hi_row.hpp"
#include "bsr/trsm_bsr_u_lo_col.hpp"
#include "bsr/trsm_bsr_u_lo_row.hpp"

#include "bsr/trsm_bsr_n_hi_col_trans.hpp"
#include "bsr/trsm_bsr_n_hi_row_trans.hpp"
#include "bsr/trsm_bsr_n_lo_col_trans.hpp"
#include "bsr/trsm_bsr_n_lo_row_trans.hpp"
#include "bsr/trsm_bsr_u_hi_col_trans.hpp"
#include "bsr/trsm_bsr_u_hi_row_trans.hpp"
#include "bsr/trsm_bsr_u_lo_col_trans.hpp"
#include "bsr/trsm_bsr_u_lo_row_trans.hpp"

#include "bsr/trsm_bsr_n_hi_col_conj.hpp"
#include "bsr/trsm_bsr_n_hi_row_conj.hpp"
#include "bsr/trsm_bsr_n_lo_col_conj.hpp"
#include "bsr/trsm_bsr_n_lo_row_conj.hpp"
#include "bsr/trsm_bsr_u_hi_col_conj.hpp"
#include "bsr/trsm_bsr_u_hi_row_conj.hpp"
#include "bsr/trsm_bsr_u_lo_col_conj.hpp"
#include "bsr/trsm_bsr_u_lo_row_conj.hpp"

#include "bsr/diagsm_bsr_n_col.hpp"
#include "bsr/diagsm_bsr_n_row.hpp"
#include "bsr/diagsm_bsr_u_col.hpp"
#include "bsr/diagsm_bsr_u_row.hpp"

#include "csc/trsm_csc_n_hi_col.hpp"
#include "csc/trsm_csc_n_hi_row.hpp"
#include "csc/trsm_csc_n_lo_col.hpp"
#include "csc/trsm_csc_n_lo_row.hpp"
#include "csc/trsm_csc_u_hi_col.hpp"
#include "csc/trsm_csc_u_hi_row.hpp"
#include "csc/trsm_csc_u_lo_col.hpp"
#include "csc/trsm_csc_u_lo_row.hpp"

#include "csc/trsm_csc_n_hi_col_trans.hpp"
#include "csc/trsm_csc_n_hi_row_trans.hpp"
#include "csc/trsm_csc_n_lo_col_trans.hpp"
#include "csc/trsm_csc_n_lo_row_trans.hpp"
#include "csc/trsm_csc_u_hi_col_trans.hpp"
#include "csc/trsm_csc_u_hi_row_trans.hpp"
#include "csc/trsm_csc_u_lo_col_trans.hpp"
#include "csc/trsm_csc_u_lo_row_trans.hpp"

#include "csc/trsm_csc_n_hi_col_conj.hpp"
#include "csc/trsm_csc_n_hi_row_conj.hpp"
#include "csc/trsm_csc_n_lo_col_conj.hpp"
#include "csc/trsm_csc_n_lo_row_conj.hpp"
#include "csc/trsm_csc_u_hi_col_conj.hpp"
#include "csc/trsm_csc_u_hi_row_conj.hpp"
#include "csc/trsm_csc_u_lo_col_conj.hpp"
#include "csc/trsm_csc_u_lo_row_conj.hpp"

#include "csc/diagsm_csc_n_col.hpp"
#include "csc/diagsm_csc_n_row.hpp"
#include "csc/diagsm_csc_u_col.hpp"
#include "csc/diagsm_csc_u_row.hpp"

#include "coo/trsm_coo_n_hi_col.hpp"
#include "coo/trsm_coo_n_hi_row.hpp"
#include "coo/trsm_coo_n_lo_col.hpp"
#include "coo/trsm_coo_n_lo_row.hpp"
#include "coo/trsm_coo_u_hi_col.hpp"
#include "coo/trsm_coo_u_hi_row.hpp"
#include "coo/trsm_coo_u_lo_col.hpp"
#include "coo/trsm_coo_u_lo_row.hpp"

#include "coo/trsm_coo_n_hi_col_trans.hpp"
#include "coo/trsm_coo_n_hi_row_trans.hpp"
#include "coo/trsm_coo_n_lo_col_trans.hpp"
#include "coo/trsm_coo_n_lo_row_trans.hpp"
#include "coo/trsm_coo_u_hi_col_trans.hpp"
#include "coo/trsm_coo_u_hi_row_trans.hpp"
#include "coo/trsm_coo_u_lo_col_trans.hpp"
#include "coo/trsm_coo_u_lo_row_trans.hpp"

#include "coo/trsm_coo_n_hi_col_conj.hpp"
#include "coo/trsm_coo_n_hi_row_conj.hpp"
#include "coo/trsm_coo_n_lo_col_conj.hpp"
#include "coo/trsm_coo_n_lo_row_conj.hpp"
#include "coo/trsm_coo_u_hi_col_conj.hpp"
#include "coo/trsm_coo_u_hi_row_conj.hpp"
#include "coo/trsm_coo_u_lo_col_conj.hpp"
#include "coo/trsm_coo_u_lo_row_conj.hpp"

#include "coo/diagsm_coo_n_col.hpp"
#include "coo/diagsm_coo_n_row.hpp"
#include "coo/diagsm_coo_u_col.hpp"
#include "coo/diagsm_coo_u_row.hpp"

#include "dia/trsm_dia_n_hi_col.hpp"
#include "dia/trsm_dia_n_hi_row.hpp"
#include "dia/trsm_dia_n_lo_col.hpp"
#include "dia/trsm_dia_n_lo_row.hpp"
#include "dia/trsm_dia_u_hi_col.hpp"
#include "dia/trsm_dia_u_hi_row.hpp"
#include "dia/trsm_dia_u_lo_col.hpp"
#include "dia/trsm_dia_u_lo_row.hpp"

#include "dia/trsm_dia_n_hi_col_trans.hpp"
#include "dia/trsm_dia_n_hi_row_trans.hpp"
#include "dia/trsm_dia_n_lo_col_trans.hpp"
#include "dia/trsm_dia_n_lo_row_trans.hpp"
#include "dia/trsm_dia_u_hi_col_trans.hpp"
#include "dia/trsm_dia_u_hi_row_trans.hpp"
#include "dia/trsm_dia_u_lo_col_trans.hpp"
#include "dia/trsm_dia_u_lo_row_trans.hpp"

#include "dia/trsm_dia_n_hi_col_conj.hpp"
#include "dia/trsm_dia_n_hi_row_conj.hpp"
#include "dia/trsm_dia_n_lo_col_conj.hpp"
#include "dia/trsm_dia_n_lo_row_conj.hpp"
#include "dia/trsm_dia_u_hi_col_conj.hpp"
#include "dia/trsm_dia_u_hi_row_conj.hpp"
#include "dia/trsm_dia_u_lo_col_conj.hpp"
#include "dia/trsm_dia_u_lo_row_conj.hpp"

#include "dia/diagsm_dia_n_col.hpp"
#include "dia/diagsm_dia_n_row.hpp"
#include "dia/diagsm_dia_u_col.hpp"
#include "dia/diagsm_dia_u_row.hpp"

#include "sky/trsm_sky_n_hi_col.hpp"
#include "sky/trsm_sky_n_hi_row.hpp"
#include "sky/trsm_sky_n_lo_col.hpp"
#include "sky/trsm_sky_n_lo_row.hpp"
#include "sky/trsm_sky_u_hi_col.hpp"
#include "sky/trsm_sky_u_hi_row.hpp"
#include "sky/trsm_sky_u_lo_col.hpp"
#include "sky/trsm_sky_u_lo_row.hpp"

#include "sky/trsm_sky_n_hi_col_trans.hpp"
#include "sky/trsm_sky_n_hi_row_trans.hpp"
#include "sky/trsm_sky_n_lo_col_trans.hpp"
#include "sky/trsm_sky_n_lo_row_trans.hpp"
#include "sky/trsm_sky_u_hi_col_trans.hpp"
#include "sky/trsm_sky_u_hi_row_trans.hpp"
#include "sky/trsm_sky_u_lo_col_trans.hpp"
#include "sky/trsm_sky_u_lo_row_trans.hpp"

#include "sky/trsm_sky_n_hi_col_conj.hpp"
#include "sky/trsm_sky_n_hi_row_conj.hpp"
#include "sky/trsm_sky_n_lo_col_conj.hpp"
#include "sky/trsm_sky_n_lo_row_conj.hpp"
#include "sky/trsm_sky_u_hi_col_conj.hpp"
#include "sky/trsm_sky_u_hi_row_conj.hpp"
#include "sky/trsm_sky_u_lo_col_conj.hpp"
#include "sky/trsm_sky_u_lo_row_conj.hpp"

#include "sky/diagsm_sky_n_col.hpp"
#include "sky/diagsm_sky_n_row.hpp"
#include "sky/diagsm_sky_u_col.hpp"
#include "sky/diagsm_sky_u_row.hpp"