#pragma once

#include "../spmat.h"

/* geam_nnz_csr*/
alphasparseStatus_t dcu_geam_nnz_csr(alphasparseHandle_t handle,
                                     ALPHA_INT m,
                                     ALPHA_INT n,
                                     ALPHA_INT nnz_A,
                                     const ALPHA_INT *csr_row_ptr_A,
                                     const ALPHA_INT *csr_col_ind_A,
                                     ALPHA_INT nnz_B,
                                     const ALPHA_INT *csr_row_ptr_B,
                                     const ALPHA_INT *csr_col_ind_B,
                                     ALPHA_INT *csr_row_ptr_C,
                                     ALPHA_INT *nnz_C);

/* spgemm_nnz_csr*/
alphasparseStatus_t dcu_spgemm_nnz_csr(alphasparseHandle_t handle,
                                       ALPHA_INT m,
                                       ALPHA_INT n,
                                       ALPHA_INT k,
                                       ALPHA_INT nnz_A,
                                       const ALPHA_INT *csr_row_ptr_A,
                                       const ALPHA_INT *csr_col_ind_A,
                                       ALPHA_INT nnz_B,
                                       const ALPHA_INT *csr_row_ptr_B,
                                       const ALPHA_INT *csr_col_ind_B,
                                       ALPHA_INT nnz_D,
                                       const ALPHA_INT *csr_row_ptr_D,
                                       const ALPHA_INT *csr_col_ind_D,
                                       ALPHA_INT *csr_row_ptr_C,
                                       ALPHA_INT *nnz_C,
                                       const alphasparse_dcu_mat_info_t info_C,
                                       void *temp_buffer);

alphasparseStatus_t dcu_spgemm_nnz_csr_transA(alphasparseHandle_t handle,
                                              ALPHA_INT m,
                                              ALPHA_INT n,
                                              ALPHA_INT k,
                                              ALPHA_INT nnz_A,
                                              const ALPHA_INT *csr_row_ptr_A,
                                              const ALPHA_INT *csr_col_ind_A,
                                              ALPHA_INT nnz_B,
                                              const ALPHA_INT *csr_row_ptr_B,
                                              const ALPHA_INT *csr_col_ind_B,
                                              ALPHA_INT nnz_D,
                                              const ALPHA_INT *csr_row_ptr_D,
                                              const ALPHA_INT *csr_col_ind_D,
                                              ALPHA_INT *csr_row_ptr_C,
                                              ALPHA_INT *nnz_C,
                                              const alphasparse_dcu_mat_info_t info_C,
                                              void *temp_buffer);

alphasparseStatus_t dcu_spgemm_nnz_csr_conjA(alphasparseHandle_t handle,
                                             ALPHA_INT m,
                                             ALPHA_INT n,
                                             ALPHA_INT k,
                                             ALPHA_INT nnz_A,
                                             const ALPHA_INT *csr_row_ptr_A,
                                             const ALPHA_INT *csr_col_ind_A,
                                             ALPHA_INT nnz_B,
                                             const ALPHA_INT *csr_row_ptr_B,
                                             const ALPHA_INT *csr_col_ind_B,
                                             ALPHA_INT nnz_D,
                                             const ALPHA_INT *csr_row_ptr_D,
                                             const ALPHA_INT *csr_col_ind_D,
                                             ALPHA_INT *csr_row_ptr_C,
                                             ALPHA_INT *nnz_C,
                                             const alphasparse_dcu_mat_info_t info_C,
                                             void *temp_buffer);

alphasparseStatus_t dcu_spgemm_nnz_csr_transB(alphasparseHandle_t handle,
                                              ALPHA_INT m,
                                              ALPHA_INT n,
                                              ALPHA_INT k,
                                              ALPHA_INT nnz_A,
                                              const ALPHA_INT *csr_row_ptr_A,
                                              const ALPHA_INT *csr_col_ind_A,
                                              ALPHA_INT nnz_B,
                                              const ALPHA_INT *csr_row_ptr_B,
                                              const ALPHA_INT *csr_col_ind_B,
                                              ALPHA_INT nnz_D,
                                              const ALPHA_INT *csr_row_ptr_D,
                                              const ALPHA_INT *csr_col_ind_D,
                                              ALPHA_INT *csr_row_ptr_C,
                                              ALPHA_INT *nnz_C,
                                              const alphasparse_dcu_mat_info_t info_C,
                                              void *temp_buffer);

alphasparseStatus_t dcu_spgemm_nnz_csr_transAB(alphasparseHandle_t handle,
                                               ALPHA_INT m,
                                               ALPHA_INT n,
                                               ALPHA_INT k,
                                               ALPHA_INT nnz_A,
                                               const ALPHA_INT *csr_row_ptr_A,
                                               const ALPHA_INT *csr_col_ind_A,
                                               ALPHA_INT nnz_B,
                                               const ALPHA_INT *csr_row_ptr_B,
                                               const ALPHA_INT *csr_col_ind_B,
                                               ALPHA_INT nnz_D,
                                               const ALPHA_INT *csr_row_ptr_D,
                                               const ALPHA_INT *csr_col_ind_D,
                                               ALPHA_INT *csr_row_ptr_C,
                                               ALPHA_INT *nnz_C,
                                               const alphasparse_dcu_mat_info_t info_C,
                                               void *temp_buffer);

alphasparseStatus_t dcu_spgemm_nnz_csr_conjAtransB(alphasparseHandle_t handle,
                                                   ALPHA_INT m,
                                                   ALPHA_INT n,
                                                   ALPHA_INT k,
                                                   ALPHA_INT nnz_A,
                                                   const ALPHA_INT *csr_row_ptr_A,
                                                   const ALPHA_INT *csr_col_ind_A,
                                                   ALPHA_INT nnz_B,
                                                   const ALPHA_INT *csr_row_ptr_B,
                                                   const ALPHA_INT *csr_col_ind_B,
                                                   ALPHA_INT nnz_D,
                                                   const ALPHA_INT *csr_row_ptr_D,
                                                   const ALPHA_INT *csr_col_ind_D,
                                                   ALPHA_INT *csr_row_ptr_C,
                                                   ALPHA_INT *nnz_C,
                                                   const alphasparse_dcu_mat_info_t info_C,
                                                   void *temp_buffer);

alphasparseStatus_t dcu_spgemm_nnz_csr_conjB(alphasparseHandle_t handle,
                                             ALPHA_INT m,
                                             ALPHA_INT n,
                                             ALPHA_INT k,
                                             ALPHA_INT nnz_A,
                                             const ALPHA_INT *csr_row_ptr_A,
                                             const ALPHA_INT *csr_col_ind_A,
                                             ALPHA_INT nnz_B,
                                             const ALPHA_INT *csr_row_ptr_B,
                                             const ALPHA_INT *csr_col_ind_B,
                                             ALPHA_INT nnz_D,
                                             const ALPHA_INT *csr_row_ptr_D,
                                             const ALPHA_INT *csr_col_ind_D,
                                             ALPHA_INT *csr_row_ptr_C,
                                             ALPHA_INT *nnz_C,
                                             const alphasparse_dcu_mat_info_t info_C,
                                             void *temp_buffer);

alphasparseStatus_t dcu_spgemm_nnz_csr_transAconjB(alphasparseHandle_t handle,
                                                   ALPHA_INT m,
                                                   ALPHA_INT n,
                                                   ALPHA_INT k,
                                                   ALPHA_INT nnz_A,
                                                   const ALPHA_INT *csr_row_ptr_A,
                                                   const ALPHA_INT *csr_col_ind_A,
                                                   ALPHA_INT nnz_B,
                                                   const ALPHA_INT *csr_row_ptr_B,
                                                   const ALPHA_INT *csr_col_ind_B,
                                                   ALPHA_INT nnz_D,
                                                   const ALPHA_INT *csr_row_ptr_D,
                                                   const ALPHA_INT *csr_col_ind_D,
                                                   ALPHA_INT *csr_row_ptr_C,
                                                   ALPHA_INT *nnz_C,
                                                   const alphasparse_dcu_mat_info_t info_C,
                                                   void *temp_buffer);

alphasparseStatus_t dcu_spgemm_nnz_csr_conjAB(alphasparseHandle_t handle,
                                              ALPHA_INT m,
                                              ALPHA_INT n,
                                              ALPHA_INT k,
                                              ALPHA_INT nnz_A,
                                              const ALPHA_INT *csr_row_ptr_A,
                                              const ALPHA_INT *csr_col_ind_A,
                                              ALPHA_INT nnz_B,
                                              const ALPHA_INT *csr_row_ptr_B,
                                              const ALPHA_INT *csr_col_ind_B,
                                              ALPHA_INT nnz_D,
                                              const ALPHA_INT *csr_row_ptr_D,
                                              const ALPHA_INT *csr_col_ind_D,
                                              ALPHA_INT *csr_row_ptr_C,
                                              ALPHA_INT *nnz_C,
                                              const alphasparse_dcu_mat_info_t info_C,
                                              void *temp_buffer);