#include "trmv_csr_n_hi.hpp"
#include "trmv_csr_n_hi_trans.hpp"
#include "trmv_csr_u_hi.hpp"
#include "trmv_csr_u_hi_trans.hpp"
#include "trmv_csr_n_lo.hpp"
#include "trmv_csr_n_lo_trans.hpp"
#include "trmv_csr_u_lo.hpp"
#include "trmv_csr_u_lo_trans.hpp"

#include "trmv_csr_n_hi_conj.hpp"
#include "trmv_csr_u_hi_conj.hpp"
#include "trmv_csr_n_lo_conj.hpp"
#include "trmv_csr_u_lo_conj.hpp"

#include "trmv_csc_n_hi.hpp"
#include "trmv_csc_n_hi_trans.hpp"
#include "trmv_csc_u_hi.hpp"
#include "trmv_csc_u_hi_trans.hpp"
#include "trmv_csc_n_lo.hpp"
#include "trmv_csc_n_lo_trans.hpp"
#include "trmv_csc_u_lo.hpp"
#include "trmv_csc_u_lo_trans.hpp"

#include "trmv_csc_n_hi_conj.hpp"
#include "trmv_csc_u_hi_conj.hpp"
#include "trmv_csc_n_lo_conj.hpp"
#include "trmv_csc_u_lo_conj.hpp"

#include "trmv_coo_n_hi.hpp"
#include "trmv_coo_n_hi_trans.hpp"
#include "trmv_coo_u_hi.hpp"
#include "trmv_coo_u_hi_trans.hpp"
#include "trmv_coo_n_lo.hpp"
#include "trmv_coo_n_lo_trans.hpp"
#include "trmv_coo_u_lo.hpp"
#include "trmv_coo_u_lo_trans.hpp"

#include "trmv_coo_n_hi_conj.hpp"
#include "trmv_coo_u_hi_conj.hpp"
#include "trmv_coo_n_lo_conj.hpp"
#include "trmv_coo_u_lo_conj.hpp"

#include "trmv_bsr_n_hi.hpp"
#include "trmv_bsr_n_hi_trans.hpp"
#include "trmv_bsr_u_hi.hpp"
#include "trmv_bsr_u_hi_trans.hpp"
#include "trmv_bsr_n_lo.hpp"
#include "trmv_bsr_n_lo_trans.hpp"
#include "trmv_bsr_u_lo.hpp"
#include "trmv_bsr_u_lo_trans.hpp"

#include "trmv_bsr_n_hi_conj.hpp"
#include "trmv_bsr_u_hi_conj.hpp"
#include "trmv_bsr_n_lo_conj.hpp"
#include "trmv_bsr_u_lo_conj.hpp"

#include "trmv_dia_n_hi.hpp"
#include "trmv_dia_n_hi_trans.hpp"
#include "trmv_dia_u_hi.hpp"
#include "trmv_dia_u_hi_trans.hpp"
#include "trmv_dia_n_lo.hpp"
#include "trmv_dia_n_lo_trans.hpp"
#include "trmv_dia_u_lo.hpp"
#include "trmv_dia_u_lo_trans.hpp"

#include "trmv_dia_n_hi_conj.hpp"
#include "trmv_dia_u_hi_conj.hpp"
#include "trmv_dia_n_lo_conj.hpp"
#include "trmv_dia_u_lo_conj.hpp"

#include "trmv_sky_n_hi.hpp"
#include "trmv_sky_n_hi_trans.hpp"
#include "trmv_sky_u_hi.hpp"
#include "trmv_sky_u_hi_trans.hpp"
#include "trmv_sky_n_lo.hpp"
#include "trmv_sky_n_lo_trans.hpp"
#include "trmv_sky_u_lo.hpp"
#include "trmv_sky_u_lo_trans.hpp"

#include "trmv_sky_n_hi_conj.hpp"
#include "trmv_sky_u_hi_conj.hpp"
#include "trmv_sky_n_lo_conj.hpp"
#include "trmv_sky_u_lo_conj.hpp"

