#include "spmmd_csr_row.hpp"
#include "spmmd_csr_row_trans.hpp"
#include "spmmd_csr_col.hpp"
#include "spmmd_csr_col_trans.hpp"
#include "spmmd_csr_row_conj.hpp"
#include "spmmd_csr_col_conj.hpp"

#include "spmmd_bsr_row.hpp"
#include "spmmd_bsr_row_trans.hpp"
#include "spmmd_bsr_col.hpp"
#include "spmmd_bsr_col_trans.hpp"
#include "spmmd_bsr_row_conj.hpp"
#include "spmmd_bsr_col_conj.hpp"

#include "spmmd_csc_row.hpp"
#include "spmmd_csc_row_trans.hpp"
#include "spmmd_csc_col.hpp"
#include "spmmd_csc_col_trans.hpp"
#include "spmmd_csc_row_conj.hpp"
#include "spmmd_csc_col_conj.hpp"